server.port=8900
spring.application.name=api-gateway

# --- EUREKA ---
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# --- ZUUL CONFIG ---
zuul.prefix=/api
zuul.ignored-services=*
zuul.sensitive-headers=Cookie,Set-Cookie

# --- ROUTES ---
# 1. User Service
zuul.routes.users.path=/accounts/**
zuul.routes.users.serviceId=user-service
zuul.routes.users.strip-prefix=true 

# 2. Product Catalog
zuul.routes.catalog.path=/catalog/**
zuul.routes.catalog.serviceId=PRODUCT-CATALOG-SERVICE
zuul.routes.catalog.strip-prefix=true

# 3. Order Service
zuul.routes.orders.path=/order/**
zuul.routes.orders.serviceId=ORDER-SERVICE
zuul.routes.orders.strip-prefix=true

# 4. Payment Service (🔥 Sửa lại Key cho khớp)
zuul.routes.payment.path=/payment/**
zuul.routes.payment.serviceId=PAYMENT-SERVICE
zuul.routes.payment.strip-prefix=true 

# --- TIMEOUT ---
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=20000
ribbon.ReadTimeout=20000
ribbon.ConnectTimeout=20000

# Loại bỏ Header thừa từ Backend để trình duyệt không chặn CORS
zuul.ignored-headers=Access-Control-Allow-Origin, Access-Control-Allow-Methods, Access-Control-Allow-Headers
# 5. Audit Service
zuul.routes.audit.path=/history/**
zuul.routes.audit.serviceId=audit-service
zuul.routes.audit.strip-prefix=true